- shell: cat '/srv/kubernetes/kubelet.pem'
  register: kubelet_pem_cmd
- shell: cat '/srv/kubernetes/kubelet-key.pem'
  register: kubelet_key_pem_cmd
- shell: cat '/srv/kubernetes/ca.pem'
  register: ca_pem_cmd
- name: write kubeconfig
  jsonnet:
    src: "kubeconfig.jsonnet"
    dest: "/srv/kubernetes/kubeconfig.json"
    mode: 0644
