#!/bin/bash

set -o errexit
set -o nounset
set -o pipefail

source "./config"

if [ -z "${NO_BUILD+x}" ] ; then
  echo "Building images for Kubernetes version ${kubernetes_release}..."
  "./build" "$@"
fi

if [ -z "${NO_PUSH+x}" ] ; then
  echo "Pushing images for Kubernetes version ${kubernetes_release}..."
  "./push" "$@"
fi
