sudo: required

addons:
  apt:
    sources:
      - debian-sid    # Grab shellcheck from the Debian repo (o_O)
    packages:
      - cabal-install

services:
  - docker

env:
  - DOCKER_RELEASE="1.10.3" WEAVE_RELEASE="v1.5.1" KUBERNETES_RELEASE="v1.2.4" FORCE_USERSPACE_PROXY="yes"

install:
  - export PATH="${HOME}/.cabal/bin:${PATH}"
  - cabal update
  - cabal install shellcheck
  - sudo service docker stop
  - sudo curl --silent --location https://get.docker.com/builds/Linux/x86_64/docker-${DOCKER_RELEASE} --output /usr/bin/docker
  - sudo chmod +x /usr/bin/docker
  - sudo service docker start
  - sudo curl --silent --location https://github.com/weaveworks/weave/releases/download/${WEAVE_RELEASE}/weave --output /usr/bin/weave
  - sudo chmod +x /usr/bin/weave
  - weave launch-router
  - weave launch-proxy --rewrite-inspect
  - weave launch-plugin
  - weave expose -h "$(hostname).weave.local"
  - weave status
  - docker ps
  - docker images
  - ps -ef | grep docker
  - systemctl cat docker || true
  - systemctl status docker || true

script:
  - ./test-shellcheck
  - ./build "${KUBERNETES_RELEASE}"
  - ./test-docker-compose
  - docker ps
  - docker images
  - weave status dns
