#!/bin/bash

set -o errexit
set -o nounset
set -o pipefail

src="$(git rev-parse --show-toplevel)"
source "${src}/config"

if [ -z "${NO_BUILD+x}" ] ; then
  echo "Building images for Kubernetes version ${kubernetes_release}..."
  "${src}/build" "$@"
fi

if [ -z "${NO_PUSH+x}" ] ; then
  echo "Pushing images for Kubernetes version ${kubernetes_release}..."
  "${src}/push" "$@"
fi
