#!/bin/bash -ex
eval "$(weave env)"

toolbox_run() {
  docker run \
    --volume="/:/rootfs" \
    --volume="/var/run/weave/weave.sock:/docker.sock" \
      "weaveworks/kubernetes-anywhere:toolbox-${KUBERNETES_RELEASE}" \
        "$@"
}

toolbox_run setup-kubelet-volumes
toolbox_run compose -p kube up -d
toolbox_run kubectl version
toolbox_run kubectl get nodes
toolbox_run kubectl create -f skydns-addon
toolbox_run kubectl create -f guestbook-example-NodePort
toolbox_run bash -c 'until [ "$(kubectl get pods --all-namespaces --no-headers | grep -v Running | wc -l)" = 0 ]; do sleep 1 ; done'
