#!/bin/bash -e

# Copyright 2015-2016 Weaveworks Ltd.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

_bin_bash=(
  "${BASH_SOURCE[0]}"
  ./build
  ./push
  ./push-only-latest-tag
  ./build-and-push
  ./test-docker-compose
  ./docker-images/toolbox-configure.sh
  ./docker-images/toolbox/scripts/*
  ./docker-images/apiserver-anywhere.sh
  ./docker-images/controller-manager-anywhere.sh
  ./docker-images/kubelet-anywhere.sh
  ./docker-images/proxy-anywhere.sh
  ./docker-images/scheduler-anywhere.sh
  ./docker-images/kubelet-cni/bin/weave-net
  ./docker-images/kubelet-cni/bin/weave-ipam
  ./examples/google-compute-engine/create-cluster.sh
  ./examples/google-compute-engine/delete-cluster.sh
)

_bin_sh=(
  ./docker-images/etcd-anywhere.sh
  ./docker-images/weave-fix-nameserver.sh
)

shellcheck -x -s bash "${_bin_bash[@]}"
shellcheck -x -s sh "${_bin_sh[@]}"
