#cloud-config

repo_update: true
repo_upgrade: all

apt_sources:
  - source: "deb https://apt.dockerproject.org/repo ubuntu-wily main"
    key: |
      -----BEGIN PGP PUBLIC KEY BLOCK-----
      mQINBFWln24BEADrBl5p99uKh8+rpvqJ48u4eTtjeXAWbslJotmC/CakbNSqOb9o
      ddfzRvGVeJVERt/Q/mlvEqgnyTQy+e6oEYN2Y2kqXceUhXagThnqCoxcEJ3+KM4R
      mYdoe/BJ/J/6rHOjq7Omk24z2qB3RU1uAv57iY5VGw5p45uZB4C4pNNsBJXoCvPn
      TGAs/7IrekFZDDgVraPx/hdiwopQ8NltSfZCyu/jPpWFK28TR8yfVlzYFwibj5WK
      dHM7ZTqlA1tHIG+agyPf3Rae0jPMsHR6q+arXVwMccyOi+ULU0z8mHUJ3iEMIrpT
      X+80KaN/ZjibfsBOCjcfiJSB/acn4nxQQgNZigna32velafhQivsNREFeJpzENiG
      HOoyC6qVeOgKrRiKxzymj0FIMLru/iFF5pSWcBQB7PYlt8J0G80lAcPr6VCiN+4c
      NKv03SdvA69dCOj79PuO9IIvQsJXsSq96HB+TeEmmL+xSdpGtGdCJHHM1fDeCqkZ
      hT+RtBGQL2SEdWjxbF43oQopocT8cHvyX6Zaltn0svoGs+wX3Z/H6/8P5anog43U
      65c0A+64Jj00rNDr8j31izhtQMRo892kGeQAaaxg4Pz6HnS7hRC+cOMHUU4HA7iM
      zHrouAdYeTZeZEQOA7SxtCME9ZnGwe2grxPXh/U/80WJGkzLFNcTKdv+rwARAQAB
      tDdEb2NrZXIgUmVsZWFzZSBUb29sIChyZWxlYXNlZG9ja2VyKSA8ZG9ja2VyQGRv
      Y2tlci5jb20+iQI4BBMBAgAiBQJVpZ9uAhsvBgsJCAcDAgYVCAIJCgsEFgIDAQIe
      AQIXgAAKCRD3YiFXLFJgnbRfEAC9Uai7Rv20QIDlDogRzd+Vebg4ahyoUdj0CH+n
      Ak40RIoq6G26u1e+sdgjpCa8jF6vrx+smpgd1HeJdmpahUX0XN3X9f9qU9oj9A4I
      1WDalRWJh+tP5WNv2ySy6AwcP9QnjuBMRTnTK27pk1sEMg9oJHK5p+ts8hlSC4Sl
      uyMKH5NMVy9c+A9yqq9NF6M6d6/ehKfBFFLG9BX+XLBATvf1ZemGVHQusCQebTGv
      0C0V9yqtdPdRWVIEhHxyNHATaVYOafTj/EF0lDxLl6zDT6trRV5n9F1VCEh4Aal8
      L5MxVPcIZVO7NHT2EkQgn8CvWjV3oKl2GopZF8V4XdJRl90U/WDv/6cmfI08GkzD
      YBHhS8ULWRFwGKobsSTyIvnbk4NtKdnTGyTJCQ8+6i52s+C54PiNgfj2ieNn6oOR
      7d+bNCcG1CdOYY+ZXVOcsjl73UYvtJrO0Rl/NpYERkZ5d/tzw4jZ6FCXgggA/Zxc
      jk6Y1ZvIm8Mt8wLRFH9Nww+FVsCtaCXJLP8DlJLASMD9rl5QS9Ku3u7ZNrr5HWXP
      HXITX660jglyshch6CWeiUATqjIAzkEQom/kEnOrvJAtkypRJ59vYQOedZ1sFVEL
      MXg2UCkD/FwojfnVtjzYaTCeGwFQeqzHmM241iuOmBYPeyTY5veF49aBJA1gEJOQ
      TvBR8Q==
      =Fm3p
      -----END PGP PUBLIC KEY BLOCK-----

packages:
  - curl
  - docker-engine

write_files:

  - path: /usr/local/bin/kubernetes-anywhere-toolbox
    permissions: '0755'
    owner: root
    content: |
      #!/bin/bash

      args="--volume=/var/run/weave/weave.sock:/docker.sock"

      if [ -n "${SSH_AUTH_SOCK}" ] ; then
        args="${volumes} --volume=${SSH_AUTH_SOCK}:/agent.sock --env=SSH_AUTH_SOCK=/agent.sock"
      fi

      exec sudo docker --host="unix:///var/run/weave/weave.sock" run \
        --tty --interactive ${args} \
          weaveworks/kubernetes-anywhere:tools $@

  - path: /etc/kubernetes-anywhere.env
    permissions: '0600'
    owner: root
    content: |
      WEAVE_INIT_PEER_COUNT="--init-peer-count 7"
      WEAVE_SCRIPT_VERSION="v1.4.4"
      ETCD_CLUSTER_SIZE="3"
      CLOUD_PROVIDER="aws"
      DOCKER_ARGS="--host=fd:// --storage-driver=overlay"

  - path: /etc/systemd/system/docker.socket
    permissions: '0644'
    owner: root
    content: |
      [Unit]
      Description=Docker Socket for the API
      PartOf=docker.service
      [Socket]
      ListenStream=/var/run/docker.sock
      SocketMode=0660
      [Install]
      WantedBy=sockets.target

  - path: /etc/systemd/system/docker.service
    permissions: '0644'
    owner: root
    content: |
      [Unit]
      Description=Docker Application Container Engine
      Documentation=http://docs.docker.com
      After=docker.socket network.target
      Requires=docker.socket
      [Service]
      EnvironmentFile=/etc/kubernetes-anywhere.env
      ExecStart=/usr/bin/docker daemon $DOCKER_ARGS
      Restart=on-failure
      LimitNOFILE=1048576
      LimitNPROC=1048576
      [Install]
      WantedBy=weave-network.target
      WantedBy=weave.service

  - path: /tmp/kubernetes-anywhere-provision.sh
    owner: root
    permissions: '0755'
    content: |
      #!/bin/bash -x

      set -o errexit
      set -o pipefail
      set -o nounset

      echo "AWS_LOCAL_HOSTNAME=\"$(hostname -f)\"" >> /etc/kubernetes-anywhere.env

      systemctl daemon-reload

      systemctl enable docker.service
      systemctl start docker.service

      docker version
      docker pull weaveworks/kubernetes-anywhere:tools
      docker images
      docker run -v /etc/systemd/system:/host-systemd weaveworks/kubernetes-anywhere:tools install-basic-systemd-units

      systemctl daemon-reload

      systemctl enable weave.service weaveproxy.service weave-expose.service weave-network.target
      systemctl start weave-network.target

      eval $(docker run weaveworks/kubernetes-anywhere:tools describe-ec2-node | tee -a /etc/kubernetes-anywhere.env)

      case "${NAME_TAG}" in
        kubernetes-etcd)
          systemctl enable etcd.service
          systemctl start etcd.service
          ;;
        kubernetes-master)
          systemctl enable kube-apiserver.service kube-scheduler.service kube-controller-manager.service kubernetes-master.target
          systemctl start kubernetes-master.target
          ;;
        kubernetes-node)
          systemctl enable kubelet.service kube-proxy.service kubernetes-node.target
          systemctl start kubernetes-node.target
          ;;
      esac

runcmd:
  - /tmp/kubernetes-anywhere-provision.sh
