#! /bin/bash

set -o errexit
set -o pipefail
set -o nounset

cd "${BASH_SOURCE%/*}"
config="./../../.config"
configjson="./../../.config.json"

gen() {
  mkdir -p .tmp/
  jsonnet -J ../../ --multi .tmp/ all.jsonnet
}

check_auth() {
  cluster_name="$(jq -r '.phase1.cluster_name' ${configjson})"
  location="$(jq -r '.phase1.azure.location' ${configjson})"
  subscription_id="$(jq -r '.phase1.azure.subscription_id' ${configjson})"
  tenant_id="$(jq -r '.phase1.azure.tenant_id' ${configjson})"
  client_id="$(jq -r '.phase1.azure.client_id' ${configjson})"
  client_secret="$(jq -r '.phase1.azure.client_secret' ${configjson})"

  if [[ -z "${client_id:-}" && -z "${client_secret}" ]]; then
    app_url="http://${cluster_name}"
    secret="$(cat /proc/sys/kernel/random/uuid)"
    while true; do
    echo
    echo "Azure 'client_id' and 'client_secret' are empty."
    echo "This will now create a ServicePrincipal named '${cluster_name}', identified by '${app_url}' which will be granted 'Contributor' access to the specific subscription."
    read -p "Proceed and create new ServicePrincipal? [y/n] " -n 1 -r && echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
      ./create-azure-service-principal.sh \
        --subscription-id=${subscription_id} \
        --name="${cluster_name}" \
        --secret="${secret}" \
        --app-url="${app_url}" \
        --output-format=text

      sed -i "s|.phase1.azure.client_id=\"\"|.phase1.azure.client_id=\"${app_url}\"|" "${config}"
      sed -i "s|.phase1.azure.client_secret=\"\"|.phase1.azure.client_secret=\"${secret}\"|" "${config}"

      gened="{\"phase1\":{\"azure\":{\
          \"client_id\": \"${app_url}\",\
          \"client_secret\": \"${secret}\"\
      }}}"

      merged="$(jq ". * ${gened}" "${configjson}")"
      echo "${merged}" > "${configjson}.tmp"
      mv "${configjson}.tmp" "${configjson}"

      echo "Sleeping for 30 seconds to prevent Terraform failures"
      sleep 30

      break
    elif [[ $REPLY =~ ^[Nn]$ ]]; then
      printf 'Credentials must be supplied.' >&2
      exit -1
    fi
    done
  fi
}

check_tenant_id() {
  subscription_id="$(jq -r '.phase1.azure.subscription_id' ${configjson})"
  tenant_id="$(curl https://management.azure.com/subscriptions/${subscription_id}?api-version=2016-01-01 -s -D - -o /dev/null | grep WWW-Authenticate | egrep '[0-9a-f]{8}-([0-9a-f]{4}-){3}[0-9a-f]{12}' -o)"

  gened="{\"phase1\":{\"azure\":{\
      \"tenant_id\": \"${tenant_id}\"\
  }}}"

  merged="$(jq ". * ${gened}" "${configjson}")"
  echo "${merged}" > "${configjson}.tmp"
  mv "${configjson}.tmp" "${configjson}"
}

check_storage_account_name() {
  storage_account_name="$(jq -r '.phase1.azure.storage_account_name' ${configjson})"
  if [[ ! -z "${storage_account_name}" ]]; then
    # everything is fine, we assume user knows what they are doing
    return 0
  fi
  set +e;
  storage_account_name="$(cat /dev/urandom | tr -dc 'a-z' | fold -w 1 | head -n 1)";
  storage_account_name="${storage_account_name}$(cat /dev/urandom | tr -dc 'a-z0-9' | fold -w 20 | head -n 1)k8s"
  set -e;

  sed -i "s|.phase1.azure.storage_account_name=\"\"|.phase1.azure.storage_account_name=\"${storage_account_name}\"|" "${config}"

  gened="{\"phase1\":{\"azure\":{\
      \"storage_account_name\": \"${storage_account_name}\"\
  }}}"
  merged="$(jq ". * ${gened}" "${configjson}")"
  echo "${merged}" > "${configjson}.tmp"
  mv "${configjson}.tmp" "${configjson}"
}

deploy() {
  check_storage_account_name
  check_tenant_id
  check_auth
  gen

  # Workaround: https://github.com/hashicorp/terraform/issues/7153
  terraform apply -state=./.tmp/terraform.tfstate .tmp ||
    terraform apply -state=./.tmp/terraform.tfstate .tmp
}

destroy() {
  if [[ "${FORCE_DESTROY:-}" == "y" ]]; then
    terraform destroy -state=./.tmp/terraform.tfstate -force .tmp
  else
    terraform destroy -state=./.tmp/terraform.tfstate .tmp
  fi
}

case "${1:-}" in
  "")
    ;;
  "deploy-cluster")
    deploy
    ;;
  "destroy-cluster")
    destroy
    ;;
  "gen")
    gen
    ;;
esac
