#! /bin/bash

set -o errexit
set -o pipefail
set -o nounset
set -x

cd "${BASH_SOURCE%/*}"

gen() {
  mkdir -p .tmp/
  jsonnet -J ../../ --multi .tmp/ all.jsonnet
}

deploy() {
  gen
  
  # Workaround: https://github.com/hashicorp/terraform/issues/7153
  terraform apply -state=./.tmp/terraform.tfstate .tmp || true
  
  # TODO: this dumps tfstate into ./azure/ rather than ./azure/.tmp/
  terraform apply -state=./.tmp/terraform.tfstate .tmp
}

destroy() {
  terraform destroy .tmp
}

case "${1:-}" in
  "")
    ;;
  "deploy")
    deploy
    ;;
  "destroy")
    destroy
    ;;
  "gen")
    gen
    ;;
esac
