#! /bin/bash

set -o errexit
set -o pipefail
set -o nounset
set -x

cd "${BASH_SOURCE%/*}"

gen() {
  jsonnet -J ../../../ --multi ./ all.jsonnet
}

deploy() {
  gen

  # Workaround: https://github.com/hashicorp/terraform/issues/7153
  terraform apply || true

  # TODO: this dumps tfstate into ./azure/ rather than ./azure/.tmp/
  terraform apply
}

destroy() {
  terraform destroy
}

case "${1:-}" in
  "")
    ;;
  "deploy")
    deploy
    ;;
  "destroy")
    destroy
    ;;
  "gen")
    gen
    ;;
esac
