#!/bin/bash -x

set -o errexit
set -o pipefail
set -o nounset

doc=$(curl --silent http://169.254.169.254/latest/dynamic/instance-identity/document)
AWS_DEFAULT_REGION=$(printf "%s" "${doc}" | jq -r .region)
export AWS_DEFAULT_REGION

instance_description=$(
  aws ec2 describe-instances \
    --instance-ids "$(printf "%s" "${doc}" | jq -r .instanceId)"
)

instance_kubernetescluster_tag=$(
  printf "%s" "${instance_description}" \
  | jq -r '.Reservations[].Instances[].Tags[] | select(.Key=="KubernetesCluster") .Value'
)

registry=$(printf "%s.dkr.ecr.%s.amazonaws.com" \
  "$(printf "%s" "${doc}" | jq -r .accountId)" \
  "$(printf "%s" "${doc}" | jq -r .region)" \
)

print_image_variable() {
  local ecr_tag="${registry}/${instance_kubernetescluster_tag}/${1}/pki:${2}"
  local upcase_name=${2^^};
  printf "KUBERNETES_ANYWHERE_%s_PKI_IMAGE=\"%s\"\n" "${upcase_name/-/_}" "${ecr_tag}"
}

for i in apiserver controller-manager scheduler
do print_image_variable master $i
done

for i in kubelet proxy toolbox
do print_image_variable node $i
done
