#!/bin/bash -x

set -o errexit
set -o pipefail
set -o nounset

doc=$(curl --silent http://169.254.169.254/latest/dynamic/instance-identity/document)
AWS_DEFAULT_REGION=$(printf "%s" "${doc}" | jq -r .region)
export AWS_DEFAULT_REGION

docker_login=($(aws ecr get-login))

exec "${docker_login[@]}"
