#!/bin/bash -x

set -o errexit
set -o pipefail
set -o nounset

doc=$(curl --silent http://169.254.169.254/latest/dynamic/instance-identity/document)
AWS_DEFAULT_REGION=$(printf "%s" "${doc}" | jq -r .region)
export AWS_DEFAULT_REGION

instance_description=$(
  aws ec2 describe-instances \
    --instance-ids "$(printf "%s" "${doc}" | jq -r .instanceId)"
)

instance_kubernetescluster_tag=$(
  printf "%s" "${instance_description}" \
  | jq -r '.Reservations[].Instances[].Tags[] | select(.Key=="KubernetesCluster") .Value'
)

aws ec2 describe-instances --filters \
    "Name=tag:KubernetesCluster,Values=${instance_kubernetescluster_tag}" \
    "Name=instance-state-name,Values=running,pending" \
  | jq -r '.Reservations[].Instances[].PrivateIpAddress | if . != null then . else empty end' \
  | xargs
