#!/bin/bash -x

# Copyright 2015-2016 Weaveworks Ltd.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -o errexit
set -o pipefail
set -o nounset

doc=$(curl --silent http://169.254.169.254/latest/dynamic/instance-identity/document)
AWS_DEFAULT_REGION=$(printf "%s" "${doc}" | jq -r .region)
export AWS_DEFAULT_REGION

instance_description=$(
  aws ec2 describe-instances \
    --instance-ids "$(printf "%s" "${doc}" | jq -r .instanceId)"
)

instance_kubernetescluster_tag=$(
  printf "%s" "${instance_description}" \
  | jq -r '.Reservations[].Instances[].Tags[] | select(.Key=="KubernetesCluster") .Value'
)

aws ec2 describe-instances --filters \
    "Name=tag:KubernetesCluster,Values=${instance_kubernetescluster_tag}" \
    "Name=instance-state-name,Values=running,pending" \
  | jq -r '.Reservations[].Instances[].PrivateIpAddress | if . != null then . else empty end' \
  | xargs
