#!/bin/bash -x

set -o errexit
set -o pipefail
set -o nounset

for unit in /etc/toolbox/systemd-units/common/* ; do
  install --mode=0644 --owner=0 --group=0 "${unit}" /host-systemd/
done
for unit in /etc/toolbox/systemd-units/with-pki/* ; do
  install --mode=0644 --owner=0 --group=0 "${unit}" /host-systemd/
done
