#!/bin/bash

set -o errexit
set -o nounset
set -o pipefail

cp /root/.kube/config /tmp/kubeconfig

kubectl \
  --kubeconfig="/tmp/kubeconfig" \
  config set-cluster local-cluster \
    --server="http://localhost:${APISERVER_LOCAL_PORT}" \
  > /dev/null

kubectl \
  --kubeconfig="/tmp/kubeconfig" \
  config set-context kubernetes-anywhere \
    --cluster="local-cluster" \
  > /dev/null

kubectl \
  --kubeconfig="/tmp/kubeconfig" \
  config view
