#!/bin/bash

# Copyright 2015-2016 Weaveworks Ltd.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

containers=($(docker ps --all --filter "label=io.k8s/KubernetesAnywhere/role" --quiet))
remove=()
for c in "${containers[@]}" ; do
  ## TODO: we can probably check if the comand is equal to $0
  role="$(docker inspect --type=container "${c}" | jq -r '.[].Config.Labels["io.k8s/KubernetesAnywhere/role"]')"
  [ "${role}" = "toolbox" ] || remove+=("${c}")
done
docker rm -f "${remove[@]}" 2> /dev/null

pki_images=($(docker images --filter "label=io.k8s/KubernetesAnywhere/pki=true" --quiet))
docker rmi -f "${pki_images[@]}" 2> /dev/null

docker rm -f kubelet-volumes

:
