#cloud-config

# Copyright 2015-2016 The Kubernetes Authors All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

repo_update: true
repo_upgrade: all

apt_sources:
  - source: "deb https://apt.dockerproject.org/repo ubuntu-xenial main"
    key: |
      -----BEGIN PGP PUBLIC KEY BLOCK-----
      mQINBFWln24BEADrBl5p99uKh8+rpvqJ48u4eTtjeXAWbslJotmC/CakbNSqOb9o
      ddfzRvGVeJVERt/Q/mlvEqgnyTQy+e6oEYN2Y2kqXceUhXagThnqCoxcEJ3+KM4R
      mYdoe/BJ/J/6rHOjq7Omk24z2qB3RU1uAv57iY5VGw5p45uZB4C4pNNsBJXoCvPn
      TGAs/7IrekFZDDgVraPx/hdiwopQ8NltSfZCyu/jPpWFK28TR8yfVlzYFwibj5WK
      dHM7ZTqlA1tHIG+agyPf3Rae0jPMsHR6q+arXVwMccyOi+ULU0z8mHUJ3iEMIrpT
      X+80KaN/ZjibfsBOCjcfiJSB/acn4nxQQgNZigna32velafhQivsNREFeJpzENiG
      HOoyC6qVeOgKrRiKxzymj0FIMLru/iFF5pSWcBQB7PYlt8J0G80lAcPr6VCiN+4c
      NKv03SdvA69dCOj79PuO9IIvQsJXsSq96HB+TeEmmL+xSdpGtGdCJHHM1fDeCqkZ
      hT+RtBGQL2SEdWjxbF43oQopocT8cHvyX6Zaltn0svoGs+wX3Z/H6/8P5anog43U
      65c0A+64Jj00rNDr8j31izhtQMRo892kGeQAaaxg4Pz6HnS7hRC+cOMHUU4HA7iM
      zHrouAdYeTZeZEQOA7SxtCME9ZnGwe2grxPXh/U/80WJGkzLFNcTKdv+rwARAQAB
      tDdEb2NrZXIgUmVsZWFzZSBUb29sIChyZWxlYXNlZG9ja2VyKSA8ZG9ja2VyQGRv
      Y2tlci5jb20+iQI4BBMBAgAiBQJVpZ9uAhsvBgsJCAcDAgYVCAIJCgsEFgIDAQIe
      AQIXgAAKCRD3YiFXLFJgnbRfEAC9Uai7Rv20QIDlDogRzd+Vebg4ahyoUdj0CH+n
      Ak40RIoq6G26u1e+sdgjpCa8jF6vrx+smpgd1HeJdmpahUX0XN3X9f9qU9oj9A4I
      1WDalRWJh+tP5WNv2ySy6AwcP9QnjuBMRTnTK27pk1sEMg9oJHK5p+ts8hlSC4Sl
      uyMKH5NMVy9c+A9yqq9NF6M6d6/ehKfBFFLG9BX+XLBATvf1ZemGVHQusCQebTGv
      0C0V9yqtdPdRWVIEhHxyNHATaVYOafTj/EF0lDxLl6zDT6trRV5n9F1VCEh4Aal8
      L5MxVPcIZVO7NHT2EkQgn8CvWjV3oKl2GopZF8V4XdJRl90U/WDv/6cmfI08GkzD
      YBHhS8ULWRFwGKobsSTyIvnbk4NtKdnTGyTJCQ8+6i52s+C54PiNgfj2ieNn6oOR
      7d+bNCcG1CdOYY+ZXVOcsjl73UYvtJrO0Rl/NpYERkZ5d/tzw4jZ6FCXgggA/Zxc
      jk6Y1ZvIm8Mt8wLRFH9Nww+FVsCtaCXJLP8DlJLASMD9rl5QS9Ku3u7ZNrr5HWXP
      HXITX660jglyshch6CWeiUATqjIAzkEQom/kEnOrvJAtkypRJ59vYQOedZ1sFVEL
      MXg2UCkD/FwojfnVtjzYaTCeGwFQeqzHmM241iuOmBYPeyTY5veF49aBJA1gEJOQ
      TvBR8Q==
      =Fm3p
      -----END PGP PUBLIC KEY BLOCK-----

packages:
  ## XXX: Need to find the way to do it with Ansible that would work on
  ## different distros. We have `maybe_install_python.sh`, but it is
  ## unclear whether it will work on CoreOS (for example), where seems
  ## like one needs to do a bit more around various bits...
  ## see:
  ## - https://github.com/defunctzombie/ansible-coreos-bootstrap
  ## - https://github.com/samsung-cnct/kraken/tree/master/ansible/roles/ansible-coreos-bootstrap
  - python
  #- docker-engine

write_files:

  - path: /etc/kubernetes-anywhere/base.env
    permissions: '0644'
    owner: root
    content: |
      WEAVE_VERSION="1.5.2"
      WEAVE_SCRIPT_VERSION="v1.5.2"
      CLOUD_PROVIDER="aws"

  - path: /etc/kubernetes-anywhere/images.env
    permissions: '0644'
    owner: root
    content: |
      KUBERNETES_ANYWHERE_TOOLBOX_IMAGE="weaveworks/kubernetes-anywhere:toolbox-v1.2.4-a5656d8"

  - path: /etc/systemd/system/docker.service.d/override.conf
    permissions: '0644'
    owner: root
    content: |
      [Service]
      MountFlags=shared
      ExecStart=
      ExecStart=/usr/bin/docker daemon --host="fd://" --storage-driver="overlay"
      Restart=on-failure
      TasksMax=infinity

  - path: /tmp/kubernetes-anywhere-bootstrap.sh
    owner: root
    permissions: '0755'
    content: |
      #!/bin/bash -x

      set -o errexit
      set -o pipefail
      set -o nounset

      systemctl daemon-reload

      ## Work around docker/docker#22599
      docker -v 2> /dev/null \
        || env DEBIAN_FRONTEND=noninteractive apt-get install \
          --assume-yes --allow-unauthenticated --force-yes \
            docker-engine

      systemctl enable docker.service
      systemctl start docker.service

      docker version

      source /etc/kubernetes-anywhere/base.env
      source /etc/kubernetes-anywhere/images.env

      toolbox="${KUBERNETES_ANYWHERE_TOOLBOX_IMAGE:-"weaveworks/kubernetes-anywhere:toolbox"}"
      docker pull "${toolbox}"

      ## The `--rm=false` is deliberate, so there are is well-known place to look for logs etc
      docker run \
        --rm=false \
        --name="kube-bootstrap" \
        --volume="/:/rootfs" \
        --env="HOME=/rootfs/root" \
        --env="DOCKER_HOST=unix:///rootfs/run/docker.sock" \
          "${toolbox}" \
            run-ansible "${CLOUD_PROVIDER}"

runcmd:
  - /tmp/kubernetes-anywhere-bootstrap.sh
