etcd:
  image: "weaveworks/kubernetes-anywhere:etcd-${KUBERNETES_RELEASE}-${KUBERNETES_ANYWHERE_REV}"
  hostname: "etcd1.weave.local"
  restart: "always"

apiserver:
  image: "weaveworks/kubernetes-anywhere:apiserver-${KUBERNETES_RELEASE}-${KUBERNETES_ANYWHERE_REV}"
  hostname: "kube-apiserver.weave.local"
  restart: "always"
  links: [ "etcd" ]
  ports: [ "${APISERVER_LOCAL_BIND}:${APISERVER_LOCAL_PORT}:${APISERVER_LOCAL_PORT}" ]
  volumes_from: [ "kube-apiserver-pki" ]
  environment:
    FORCE_LOCAL_APISERVER: "yes"
    APISERVER_LOCAL_PORT:

scheduler:
  image: "weaveworks/kubernetes-anywhere:scheduler-${KUBERNETES_RELEASE}-${KUBERNETES_ANYWHERE_REV}"
  hostname: "kube-scheduler.weave.local"
  restart: "always"
  links: [ "apiserver" ]
  volumes_from: [ "kube-scheduler-pki" ]

controller-manager:
  image: "weaveworks/kubernetes-anywhere:controller-manager-${KUBERNETES_RELEASE}-${KUBERNETES_ANYWHERE_REV}"
  hostname: "kube-controller-manager.weave.local"
  restart: "always"
  links: [ "apiserver" ]
  volumes_from: [ "kube-controller-manager-pki" ]

kubelet:
  privileged: true
  net: host
  pid: host
  image: "weaveworks/kubernetes-anywhere:kubelet-${KUBERNETES_RELEASE}-${KUBERNETES_ANYWHERE_REV}"
  restart: "always"
  volumes_from: [ "kubelet-volumes", "kubelet-pki" ]
  environment:
    USE_CNI:
    WEAVE_VERSION:

proxy:
  privileged: true
  net: host
  pid: host
  image: "weaveworks/kubernetes-anywhere:proxy-${KUBERNETES_RELEASE}-${KUBERNETES_ANYWHERE_REV}"
  restart: "always"
  volumes_from: [ "kube-proxy-pki" ]
  environment:
    USE_CNI:
    FORCE_USERSPACE_PROXY:
