#! /bin/bash

set -o errexit
set -o pipefail
set -o nounset

usage() {
  cat <<EOF >&2
$0: <.config-file-path>
EOF
}

if [[ "$#" != 1 ]]; then
  usage
  exit 1
fi

KCONFIG="$1"

read_input_and_strip_comments() {
  sed -r -e '/^(\s*#.*)?$/d' "${KCONFIG}"
}

convert_boolean_types() {
  sed -e 's/\(=\)[yY]$/\1true/' -e 's/\(=\)[nN]$/\1false/'
}

## `jq -n ".foo=true|.bar=false"` will generate `{ "foo": true, "bar": false }`
unflat="$(read_input_and_strip_comments | convert_boolean_types)"
flat=""
for line in $unflat; do
	flat="${flat}|${line}"
done
flat=${flat#"|"}
jq -n "${flat}"
