#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

wait_duration=10

num_nodes="$(( $(cat ./.config.json | jq -r '.phase1.num_nodes') + 1 ))"

while true; do
  hcount=$(kubectl get nodes 2>/dev/null | grep 'Ready' | wc -l) || true
  [[ "${hcount}" -ge "${num_nodes}" ]] && exit

  echo "Cluster is not yet healthy. Number of nodes: wanted:${num_nodes} actual:${hcount}"
  echo "Waiting ${wait_duration}"
  sleep ${wait_duration}
done

echo "Cluster is healthy!"
