#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset
set -x

cd "${BASH_SOURCE%/*}"

CONFIG_FILE="${CONFIG_JSON_FILE:-../.config.json}"
TMP_DIR=$(jq -r '.phase1.cluster_name' ${CONFIG_FILE})/.tmp

gen() {
	mkdir -p ${TMP_DIR}
	jsonnet --multi ${TMP_DIR} --tla-code-file cfg=${CONFIG_FILE} all.jsonnet
}

deploy() {
	gen
	mkdir -p /tmp/kubectl/
	HOME=/tmp/kubectl kubectl apply -f ./${TMP_DIR}
}


case "${1:-}" in
  "")
    ;;
  "deploy")
    deploy
    ;;
  "gen")
    gen
    ;;
esac
