#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset
set -x

gen() {
	cd "${BASH_SOURCE%/*}"
	mkdir -p .tmp/
	jsonnet --multi .tmp/ --tla-code-file cfg=../.config.json all.jsonnet
}

deploy() {
	gen
	mkdir -p /tmp/kubectl/
	HOME=/tmp/kubectl kubectl apply -f ./.tmp/
}


case "${1:-}" in
  "")
    ;;
  "deploy")
    deploy
    ;;
  "gen")
    gen
    ;;
esac
