#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset
set -x

cd "${BASH_SOURCE%/*}"

TMP_DIR=$(jq -r '.phase1.cluster_name' ../.config.json)/.tmp

gen() {
	mkdir -p ${TMP_DIR}
	jsonnet --multi ${TMP_DIR} --tla-code-file cfg=../.config.json all.jsonnet
}

deploy() {
	gen
	mkdir -p /tmp/kubectl/
	HOME=/tmp/kubectl kubectl apply -f ./${TMP_DIR}
}


case "${1:-}" in
  "")
    ;;
  "deploy")
    deploy
    ;;
  "gen")
    gen
    ;;
esac
