#!/bin/bash -x

# Copyright 2016 The Kubernetes Authors All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -o errexit
set -o pipefail
set -o nounset

create-pki-containers

doc=$(curl --silent http://169.254.169.254/latest/dynamic/instance-identity/document)
AWS_DEFAULT_REGION=$(printf "%s" "${doc}" | jq -r .region)
export AWS_DEFAULT_REGION

instance_description=$(
  aws ec2 describe-instances \
    --instance-ids "$(printf "%s" "${doc}" | jq -r .instanceId)"
)

instance_kubernetescluster_tag=$(
  printf "%s" "${instance_description}" \
  | jq -r '.Reservations[].Instances[].Tags[] | select(.Key=="KubernetesCluster") .Value'
)

registry=$(printf "%s.dkr.ecr.%s.amazonaws.com" \
  "$(printf "%s" "${doc}" | jq -r .accountId)" \
  "$(printf "%s" "${doc}" | jq -r .region)" \
)

tag_and_push() {
  local ecr_tag="${registry}/${instance_kubernetescluster_tag}/${1}/pki:${2}"
  docker tag "kubernetes-anywhere:${2}-pki" "${ecr_tag}"
  docker push "${ecr_tag}"
}

for i in apiserver controller-manager scheduler
do tag_and_push master $i
done

for i in kubelet proxy toolbox
do tag_and_push node $i
done
