#!/bin/bash -x

# Copyright 2015-2016 Weaveworks Ltd.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -o errexit
set -o pipefail
set -o nounset

doc=$(curl --silent http://169.254.169.254/latest/dynamic/instance-identity/document)
AWS_DEFAULT_REGION=$(printf "%s" "${doc}" | jq -r .region)
export AWS_DEFAULT_REGION

instance_description=$(
  aws ec2 describe-instances \
    --instance-ids "$(printf "%s" "${doc}" | jq -r .instanceId)"
)

instance_kubernetescluster_tag=$(
  printf "%s" "${instance_description}" \
  | jq -r '.Reservations[].Instances[].Tags[] | select(.Key=="KubernetesCluster") .Value'
)

registry=$(printf "%s.dkr.ecr.%s.amazonaws.com" \
  "$(printf "%s" "${doc}" | jq -r .accountId)" \
  "$(printf "%s" "${doc}" | jq -r .region)" \
)

print_image_variable() {
  local ecr_tag="${registry}/${instance_kubernetescluster_tag}/${1}/pki:${2}"
  local upcase_name=${2^^};
  printf "KUBERNETES_ANYWHERE_%s_PKI_IMAGE=\"%s\"\n" "${upcase_name/-/_}" "${ecr_tag}"
}

for i in apiserver controller-manager scheduler
do print_image_variable master $i
done

for i in kubelet proxy toolbox
do print_image_variable node $i
done
